[package]
name = "aoc-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy-regex = "0.12.0"
itertools = "0.12.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
